# Generated by Django 6.0.7 on 2026-08-12 12:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standardpages', '0002_alter_standardpage_body_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_images',
            field=wagtail.fields.StreamField([('image', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alternative text for accessibility.', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('alt_text', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_members',
            field=wagtail.fields.StreamField([('member', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 150, 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('name', 1), ('position', 2), ('description', 3), ('twitter_url', 4), ('facebook_url', 4), ('linkedin_url', 4), ('instagram_url', 4)]], {})}),
        ),
    ]
