# Generated by Django 6.0.7 on 2026-08-12 11:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='agents',
            field=wagtail.fields.StreamField([('agent', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Agent Image', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Real Estate Agent', 'label': 'Designation', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Twitter URL', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'Facebook URL', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'LinkedIn URL', 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'Instagram URL', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 0), ('name', 1), ('designation', 2), ('description', 3), ('twitter', 4), ('facebook', 5), ('linkedin', 6), ('instagram', 7)]], {})}, verbose_name='Agents'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='agents_description',
            field=models.TextField(blank=True, verbose_name='Agents Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='agents_title',
            field=models.CharField(blank=True, default='Our Agents', max_length=255, verbose_name='Agents Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='counters',
            field=wagtail.fields.StreamField([('counter', 2)], blank=True, block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'label': 'Number', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('number', 0), ('label', 1)]], {})}, verbose_name='Counters'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_button_text',
            field=models.CharField(blank=True, default='Apply for Real Estate agent', max_length=100, verbose_name='CTA Button Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_button_url',
            field=models.URLField(blank=True, verbose_name='CTA Button URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_title',
            field=models.CharField(blank=True, default='Be a part of our growing real state agents', max_length=255, verbose_name='CTA Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Example: flaticon-house', 'label': 'Icon Class', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'label': 'Link Text', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Link', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2), ('link_text', 3), ('link', 4)]], {})}, verbose_name='Features'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='find_home_description',
            field=models.TextField(blank=True, verbose_name='Find Home Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='find_home_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Find Home Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='find_home_title',
            field=models.CharField(blank=True, default="Let's find home that's perfect for you", max_length=255, verbose_name='Find Home Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Hero Background'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, default='Easiest way to find your dream home', max_length=255, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_features',
            field=wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Example: icon-home2', 'label': 'Icon Class', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2)]], {})}, verbose_name='Home Features'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='properties',
            field=wagtail.fields.StreamField([('property', 7)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Property Image', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Price', 'max_length': 100, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Address', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'City', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': '2 beds', 'label': 'Beds', 'max_length': 50, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': '2 baths', 'label': 'Baths', 'max_length': 50, 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'Property URL', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 0), ('price', 1), ('address', 2), ('city', 3), ('beds', 4), ('baths', 5), ('link', 6)]], {})}, verbose_name='Properties'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='properties_button_text',
            field=models.CharField(blank=True, default='View all properties', max_length=100, verbose_name='Properties Button Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='properties_button_url',
            field=models.URLField(blank=True, verbose_name='Properties Button URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='properties_title',
            field=models.CharField(blank=True, default='Popular Properties', max_length=255, verbose_name='Properties Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_button_text',
            field=models.CharField(blank=True, default='Search', max_length=100, verbose_name='Search Button Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_placeholder',
            field=models.CharField(blank=True, default='Your ZIP code or City. e.g. New York', max_length=255, verbose_name='Search Placeholder'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonial', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Person Image', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Designation', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Testimonial', 'required': False}), 4: ('wagtail.blocks.IntegerBlock', (), {'default': 5, 'label': 'Rating', 'max_value': 5, 'min_value': 1, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('name', 1), ('designation', 2), ('content', 3), ('rating', 4)]], {})}, verbose_name='Testimonials'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_title',
            field=models.CharField(blank=True, default='Customer Says', max_length=255, verbose_name='Testimonials Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section', 3), ('cta', 13), ('statistics', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'components/streamfield/blocks/heading2_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3'], 'template': 'components/streamfield/blocks/paragraph_block.html'}), 2: ('wagtail.blocks.StreamBlock', [[('paragraph', 1)]], {}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('page', 5), ('title', 6)]], {}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('link', 8), ('title', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('internal', 7), ('external', 10)]], {}), 12: ('wagtail.blocks.TextBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('heading', 4), ('link', 11), ('description', 12)]], {}), 14: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'If checked, the heading will be hidden from view and avaliable to screen-readers only.', 'label': 'Screen reader only label', 'required': False}), 15: ('wagtail.snippets.blocks.SnippetChooserBlock', ('utils.Statistic',), {}), 16: ('wagtail.blocks.ListBlock', (15,), {'max_num': 3, 'min_num': 3}), 17: ('wagtail.blocks.StructBlock', [[('heading', 4), ('sr_only_label', 14), ('statistics', 16)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_section_title',
            field=models.TextField(blank=True, verbose_name='Featured Section Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta',
            field=wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('page', 0), ('title', 1)]], {})}, verbose_name='Hero CTA'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='Introduction'),
        ),
    ]
