# Generated by Django 6.0.7 on 2026-08-13 04:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_agents_homepage_agents_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section', 3), ('cta', 13), ('statistics', 17), ('agents', 30)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'components/streamfield/blocks/heading2_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3'], 'template': 'components/streamfield/blocks/paragraph_block.html'}), 2: ('wagtail.blocks.StreamBlock', [[('paragraph', 1)]], {}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('page', 5), ('title', 6)]], {}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('link', 8), ('title', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('internal', 7), ('external', 10)]], {}), 12: ('wagtail.blocks.TextBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('heading', 4), ('link', 11), ('description', 12)]], {}), 14: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'If checked, the heading will be hidden from view and avaliable to screen-readers only.', 'label': 'Screen reader only label', 'required': False}), 15: ('wagtail.snippets.blocks.SnippetChooserBlock', ('utils.Statistic',), {}), 16: ('wagtail.blocks.ListBlock', (15,), {'max_num': 3, 'min_num': 3}), 17: ('wagtail.blocks.StructBlock', [[('heading', 4), ('sr_only_label', 14), ('statistics', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Section Title', 'max_length': 200, 'required': True}), 19: ('wagtail.blocks.TextBlock', (), {'label': 'Section Description', 'required': False}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Agent Image', 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 100, 'required': True}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Designation', 'max_length': 150, 'required': False}), 23: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 24: ('wagtail.blocks.URLBlock', (), {'label': 'Twitter URL', 'required': False}), 25: ('wagtail.blocks.URLBlock', (), {'label': 'Facebook URL', 'required': False}), 26: ('wagtail.blocks.URLBlock', (), {'label': 'LinkedIn URL', 'required': False}), 27: ('wagtail.blocks.URLBlock', (), {'label': 'Instagram URL', 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('image', 20), ('name', 21), ('designation', 22), ('description', 23), ('twitter', 24), ('facebook', 25), ('linkedin', 26), ('instagram', 27)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'label': 'Agents', 'min_num': 1}), 30: ('wagtail.blocks.StructBlock', [[('title', 18), ('description', 19), ('agents', 29)]], {})}),
        ),
    ]
